C0D1NG/Algorithms

Searching/pradumio_linear_search.cpp

Added Solution of Linear search algorithm using CPP language.

Added Linear Search Solution in CPP

---

Sorting/frbio_Selection_sort.cpp

CPP program for Selection sort.

Added selection-sort

---

Sorting/frbio_Selection_sort.cpp
Sorting/frbio_quick_sort.py

Added quick sort algorithm in python.

Quick sort

---

Sorting/frbio_merge_sort.py

Added merge sort algorithm in python.

Added merge sort algorithm

---

Searching/BhaktiChindhe_linear_search.cpp

Linear Search

---

Sorting/sharmasourab93_bubble_sort.py

Added a Bubble Sort Algorithm in Python

Hacktoberfest sharmasourab93

---

Sorting/tauseefmohammed2_BubbleSort.cpp

Implementation of Bubble Sort in C++ 
Added username before File Name as Mentioned 
Issue #2

Bubble Sort in C++ as per (Issue #2)

---

Graph/sameer-j_BFS.cpp

Algorithm implemented - Breadth First Search
Language: C++

Graph-Breadth First Search (BFS)

---

Searching/MeeeCoder_BinarySearch.cpp
Searching/MeeeCoder_LinearSearch.cpp

- add MeeeCoder_LinearSearch.cpp in Searching folder of Algorithms

create  MeeeCoder_LinearSearch.cpp

---

BInary Tree/rahul_binary_tree-Height.java
Searching/rahul_binary_search.java
Searching/rahul_linear_search.java

I have coded binary search solution in java.

Binary Search Solution in Java

---

Sorting/SparshGarg_Bubble_Sort.java

SparshGarg_Bubble_Sort.java

---

Sorting/daksh_selection_sort.cpp

I have added the file for selection sort in the Sorting Folder in the repo.

Adding Selection Sort

---

Searching/kashika3101_LinearSearch.cpp

A recursive method for the implementation of Linear Search Algorithm
Description: Recursive approach for Linear Search Algorithm to find element along with it's index in an unsorted array.

kashika3101_LinearSearch.cpp

---

BInary Tree/heap.py

I added the heap structure in object oriented python. 
Its has the methods "insert" to insert a node with a value and "removeMin" to remove the node with the minimum value.

Added heap structure in python

---

Graph/BFS_slide.cpp
Graph/BFS_slide.java
Graph/BFS_slide.py
Graph/DFS.cpp
Graph/DFS.java
Graph/DFS.py
Graph/DFS_Recursion.cpp
Graph/DFS_Recursion.java
Graph/DFS_Recursion.py

This is a quick implementation with DFS and BFS for Graph Search.
This commit to solve the Issue #17 #16 in your repo.
For more infomation, check out the comment of the code.
This is a contribute for hacktoberfest 2020.
Have a good day.

Adding DFS and BFS in Java/C++/Python to Graph Algorithms Solve [Issue #17 #16]

---

Searching/hrishikesharma_Binary_Search.py

iterative binary seach

---

Searching/AishaSaman_linearSearchPython.ipynb

Linear Search Algorithm in Python
#hacktoberfest2020

Linear Search Algorithm in Python

---

Searching/m-e-r-l-i-n_binary_search.java

binary search

---

Sorting/kanika_quick_sort.cpp

An efficient code for Quicksort Algorithm in CPP

Quicksort Code in CPP

---

Sorting/Rudransh_quick_sort.java

Here's my submission for quicksort code in java.

Quick sort code in java

---

Graph/Lashuk1729_Depth_FIrst_Search.py

Added Python code for Depth First Search using adjacency list

---

Sorting/BubbleSort.java

Bubble sort using java added

---

BInary Tree/heap.py
Searching/Sohamraje137_Templated_Basic_Linear_Search.cpp

I like writing Generic codes. 
This is a basic version of a templated linear search.

Templated_Linear_Search

---

Searching/ernesto-ca_LinearSearch.py

Hi! this is a simple example of a linked list in data structure with linear search.
i hope it is easy to  understand!

Added a data structure linear search

---

Searching/Abhinav_ternarySearch.rb

Ternary search is a divide and conquer algorithm that can be used to find an element in an array. It is similar to binary search where we divide the array into two parts but in this algorithm.
Time Complexity: O(log n base 3)

Added Ternary Search implementation in Ruby

---

Sorting/havanoor_QuickSort.cpp

Quick sort in C++

---

Sorting/Insertion Sort.c
Sorting/Quick Sort.c

I have added a code which Shorts integer value.

Insertion Sort in C .

---

Graph/sunmeetoberoi_Breadth-first Search.cpp

Performs Breadth-first search on a graph. #16

Added Breadth-first Search

---

Searching/aansh_linear_search.cpp

Added linear search program in c++ language

#1  Linear search code added

---

Dynamic Programming/largest-divisible-pair-subset.cpp

added largest divisble pair subset to dynamic programming

---

Sorting/bubblesort.cpp

added bubble sort

---

Searching/tauseefmohammed2_BinarySearch.cpp

Added Implementation of Binary Search in C++
Added username before file name as mentioned.
Issue #8

Binary Search in C++ as per (Issue #8)

---

Divide and Conquer/tushar2407_gcd.java

I have implemented the program to calculate gcd of 2 numbers in java via the Euclidean algorithm.

GCD implemented in java

---

Searching/kashika3101_BinarySearch.cpp

Description-
Utilizing binarySearch() as a recursive function to find the required element in the sorted array using binary search.

kashika3101_BinarySearch.cpp

---

Sorting/veldakarimi_bubblesort.py

I have added a bubble sort algorithm using Python

addition of bubble sort algorithm in python

---

Graph/DFS_recursive.cpp

Added code for DFS (recursive) in C++.

Add DFS_recursive.cpp

---

Graph/veldakarimi_Breadthfirstsearch.py

I have added a Breadth-First Search Algorithm using Python

addition of breadth first search algorithm using python

---

Sorting/merge_sort.c

Add the file

---

Sorting/MeeeCoder_BubbleSort.cpp

add MeeeCoder_BubbleSort.cpp in Sorting of Algorithms

add MeeeCoder_BubbleSort.cpp

---

Sorting/AdeshChoudhar19_insertion_sort.c

Insertion Sort in C

---

Sorting/ernesto-ca_QuickSort.java

The program is currently documented for you!

Quick Sort in java!

---

Arrays/quickSelect.js

I have added a quickSelect JavaScript algorithm to the list of algorithms

Added JavaScript algorithm

---

Dynamic Programming/knapsack_topDown.py

An implementation using python of the knapsack problem using a top-down approach.
Reference issue: #158

Knapsack using a topdownn approach.

---

Graph/sps619_depth_first_search.java

This pull request is regarding the issue #17 
And a hacktoberfest contribution.

sps619_depth_first_search.java

---

Searching/BInarySearch_using_Iterative_Method.cpp
Searching/BInarySearch_using_Iterative_Method_Krishna.cpp
Searching/BInarySearch_using_Recursive_Method.cpp
Searching/BInarySearch_using_Recursive_Method_Krishna.cpp
Sorting/BubbleSorting/BubbleSort._Krishna_Dawalkarcpp.c

I have added a C++ program for sorting using BubbleSort technique.
This program is added in the folder Algorithms  ->   C++   ->  with file name 'BubbleSort_Krishna_Dawalkar.cpp'
Hope u find it useful and needful : )

Added the BubbleSort Sorting Techinique

---

Sorting/amritanshusikdar_merge-sort.cpp

Added algorithm for Merge Sort in C++

add mergesort in cpp

---

Sorting/OddorEven.py

-Adding simple Odd or Even algorithm for Python.

Adding OddorEven algorithm for Python.

---

Dynamic Programming/Python/longest_increasing_subsequences.py

"The longest common subsequence (LCS) problem is the problem of finding the longest subsequence common to all sequences in a set of sequences (often just two sequences). It differs from the longest common substring problem: unlike substrings, subsequences are not required to occupy consecutive positions within the original sequences. The longest common subsequence problem is a classic computer science problem, the basis of data comparison programs such as the diff utility, and has applications in computational linguistics and bioinformatics. It is also widely used by revision control systems such as Git for reconciling multiple changes made to a revision-controlled collection of files." - by Wikipedia. 
I'd like to contribute my implementation of LCS for your Algorithms repo as …

Add longest common subsequence problem (LCS)

---

Searching/Binary_Search.py

Added Implement Binary Search #8

Binary_Search.py

---

Sorting/mafiamamba_Insertion sort.c

Added C program to implement the insertion sort, for the issue: Implement Insertion Sort #9

C program to implement insertion sort

---

Graph/ankitramtriya_DFS.java

DFS traversal in JAVA

---

Graph/ankitramtriya_BFS.java
Searching/BinarySearch_ankitramtriya.java

BFS traversal and Binary search in Java

---

Sorting/C/Kth smallest element.c

this is an algo to find kth smallest using partition (Quick Select)

Create Kth smallest element.c

---

Searching/C++/HANS-2002_linear-search.cpp
Searching/C/HANS-2002_linear-search.c

Added linear search in C and C++

---

.gitignore

- Add .gitignore file to ignore the main IDEs & compilers frequently used.

Add .gitignore for main IDEs

---

Sorting/Java/Counting_Sort.java

Implemented Counting Sort in Java

Added Counting Sort Java implementation
